### ISSUE TITLE
Compare to best practices from Jenkins LTS formula

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/homebrew-jenkins-slave#7]
https://github.com/Homebrew/homebrew-core/blob/61dcad8957f771f042da0ed4d227dd82ad52f6d3/Formula/jenkins-lts.rb

This issue is to make a best practice comparison and updates this formula to use those practices.

@CAMOBAP795 could you help with this? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse I have some questions

 - Should `jenkins-slave` starts at startup (after a reboot for example)
 - To remove a command from being in history it should be preceded with space like `"  set secret=XXX"`

**Comment by ronaldtse** [comment]
> Should jenkins-slave starts at startup (after a reboot for example)

Yes.

> To remove a command from being in history it should be preceded with space like " set secret=XXX"

OK

**Comment by CAMOBAP795** [comment]
> > To remove a command from being in history it should be preceded with space like " set secret=XXX"

> OK

I mean I will update post install message to inform about this

**Comment by CAMOBAP795** [comment]
Ok list of actions to improve `jenkins-slave` formula:
 - Add travisci & tests
 - Add `plist_options :startup => true`

**Comment by CAMOBAP795** [comment]
https://github.com/CAMOBAP795/homebrew-jenkins-slave/commit/bd9423f0902f9e03072da0f959601476c3cdc926

**Comment by ronaldtse** [comment]
@CAMOBAP795 the problem is that the user must replace the username/password before the service can get started. In bd9423f, the service has already started but does not have credentials?

**Comment by CAMOBAP795** [comment]
@ronaldtse I got that point, nothing changed in this aspect, we still keep the message with sed command how to replace credentials

I just added dummy test to check if Java part works

**Comment by ronaldtse** [comment]
@CAMOBAP795 but all this is gone:

```
       If you want to start on machine boot, use `sudo`:
       sudo brew services start riboseinc/jenkins-slaves/jenkins-slave		
		
       If you want to start on login, just do this:				
       brew services start riboseinc/jenkins-slaves/jenkins-slave		
		
		
     *Ignore what brew tells you below!*		
     -------------vvvvvvv-------------		
      \\------------vvvvv------------/		
       \\------------vvv------------/		
        \\------------v------------/
```

**Comment by CAMOBAP795** [comment]
Currently full output looks like this

```
$ brew install jenkins-slave
==> Installing jenkins-slave from travis/testtap
==> Downloading https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/remotin
######################################################################## 100.0%
==> Caveats
WARNING:
  You must configure the JENKINS_URL and JENKINS_SECRET variables in the plist file:
Step 1: Set your JENKINS_URL / JENKINS_SECRET in the environment:
  export url="https://my-jenkins.com/computer/agentname/slave-agent.jnlp"
  export secret="bd38130d1412b54287a00a3750bd100c"
Step 2: Insert the JENKINS_URL / JENKINS_SECRET in the plist and ensure that JENKINS_SECRET is not stored in the bash history:
  sed -i "" "s@REPLACE_ME_JENKINS_URL@${url}@" /usr/local/opt/jenkins-slave/com.ribose.jenkins.slave.plist
  sed -i "" "s@REPLACE_ME_JENKINS_SECRET@${secret}@" /usr/local/opt/jenkins-slave/com.ribose.jenkins.slave.plist
  unset HISTFILE url secret
To have launchd start travis/testtap/jenkins-slave now and restart at startup:
  sudo brew services start travis/testtap/jenkins-slave
==> Summary
🍺  /usr/local/Cellar/jenkins-slave/3.30: 5 files, 776KB, built in 4 seconds
```

So I just replaced:
```
If you want to start on machine boot, use `sudo`:
  sudo brew services start riboseinc/jenkins-slaves/jenkins-slave		
		
If you want to start on login, just do this:				
  brew services start riboseinc/jenkins-slaves/jenkins-slave
```

With default message
```
To have launchd start travis/testtap/jenkins-slave now and restart at startup:
  sudo brew services start travis/testtap/jenkins-slave
```

In my opinion, they look similar, + default message cares about actual `tap` names

**Comment by ronaldtse** [comment]
There is actually a reason why I specified both messages. If the Jenkins slave is launched on boot, it will not have access to the UI. If the Jenkins slave is launched on login, it can launch UI apps. 

That’s why the user needs to choose which method is appropriate. And therefore it is important for the user to ignore the default brew services message.

**Comment by CAMOBAP795** [comment]
@ronaldtse got you, let me put the original message back

**Comment by CAMOBAP795** [comment]
@ronaldtse ready to be closed I think

**Comment by ronaldtse** [comment]
Yup, thanks!
